itmx_kaggle:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "../data/{{ env_var('DUCKDB_FILENAME', 'itmx_kaggle.duckdb') }}"
      threads: "{{ env_var('DBT_THREADS', '4') | int }}"

    prod:
      type: duckdb
      path: "../data/{{ env_var('DUCKDB_FILENAME', 'itmx_kaggle.duckdb') }}"
      threads: "{{ env_var('DBT_THREADS', '8') | int }}"

    docker:
      type: duckdb
      path: "/data/duckdb/{{ env_var('DUCKDB_FILENAME', 'itmx_kaggle.duckdb') }}"
      threads: "{{ env_var('DBT_THREADS', '4') | int }}"