version: '3.8'

services:
  # Simple DuckDB file server
  duckdb:
    image: python:3.11-slim
    command: python -m http.server 8080
    working_dir: /data
    volumes:
      - ${DOCKER_DATA_VOLUME:-./data:/data}
    ports:
      - "8080:8080"
    networks:
      - ${DOCKER_NETWORK:-pipeline-network}
    environment:
      - DUCKDB_PATH=${DUCKDB_PATH:-data/itmx_kaggle.duckdb}

  # Spark with custom build (includes dependencies)
  spark:
    build:
      context: .
      dockerfile: .docker/Dockerfile.spark
    image: itmx-kaggle/spark:latest
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_NO_DAEMONIZE=true
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY:-2g}
      - SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES:-2}
    ports:
      - "8081:8080"  # Spark UI
      - "7077:7077"  # Spark master port
    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ${DOCKER_DATA_VOLUME:-./data:/data}
    networks:
      - ${DOCKER_NETWORK:-pipeline-network}

  # Prefect server with custom build (includes all dependencies)
  prefect:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prefect
    image: itmx-kaggle/prefect:latest
    command: prefect server start --host ${PREFECT_SERVER_HOST:-0.0.0.0}
    ports:
      - "${PREFECT_SERVER_PORT:-4200}:4200"
    volumes:
      - ./flows:/app/flows
      - ./config.py:/app/config.py
      - ./prefect_utils.py:/app/prefect_utils.py
      - ./dbt:/app/dbt
      - ${DOCKER_DATA_VOLUME:-./data:/data}
      - ./.env:/app/.env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL:-http://localhost:4200/api}
      - PREFECT_SERVER_API_HOST=${PREFECT_SERVER_HOST:-0.0.0.0}
      - DUCKDB_PATH=${DUCKDB_PATH:-data/itmx_kaggle.duckdb}
      - KAGGLE_DATA_PATH=${KAGGLE_DATA_PATH:-data/raw/kaggle}
      - DATA_RAW_PATH=${DATA_RAW_PATH:-data/raw}
      - DATA_PROCESSED_PATH=${DATA_PROCESSED_PATH:-data/processed}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - ${DOCKER_NETWORK:-pipeline-network}

networks:
  pipeline-network:
    driver: bridge
    name: ${DOCKER_NETWORK:-pipeline-network}